# Generated by Django 4.0.3 on 2022-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('upholstery', models.CharField(max_length=250, verbose_name='Обивка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Кресло',
                'verbose_name_plural': 'Кресла',
            },
        ),
        migrations.CreateModel(
            name='Diningtables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Обеденный стол',
                'verbose_name_plural': 'Обеденный столы',
            },
        ),
        migrations.CreateModel(
            name='Sofas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('upholstery', models.CharField(max_length=250, verbose_name='Обивка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Диван',
                'verbose_name_plural': 'Диваны',
            },
        ),
    ]
