# Generated by Django 4.0.3 on 2022-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedsidetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('colorLDSP', models.CharField(max_length=250, verbose_name='Цвет ЛДСП')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Тумба',
                'verbose_name_plural': 'Тумбы',
            },
        ),
        migrations.CreateModel(
            name='Coffeetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара 1')),
                ('price2', models.CharField(max_length=100, verbose_name='Цена товара 2')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Журнальный стол',
                'verbose_name_plural': 'Журнальные столы',
            },
        ),
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара 1')),
                ('price2', models.CharField(max_length=100, verbose_name='Цена товара 2')),
                ('tabletop', models.CharField(max_length=250, verbose_name='Столешница')),
                ('description', models.CharField(max_length=250, verbose_name='Описание товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Консоль',
                'verbose_name_plural': 'Консоли',
            },
        ),
        migrations.CreateModel(
            name='Diningchairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('description', models.CharField(max_length=250, verbose_name='Описание товара')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Обеденный стул',
                'verbose_name_plural': 'Обеденные стулья',
            },
        ),
        migrations.CreateModel(
            name='Poufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('upholstery', models.CharField(max_length=250, verbose_name='Обивка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Банкетка и пуф',
                'verbose_name_plural': 'Банкетки и пуфы',
            },
        ),
        migrations.CreateModel(
            name='Shelving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет каркаса')),
                ('price', models.CharField(max_length=100, verbose_name='Цена товара 1')),
                ('price2', models.CharField(max_length=100, verbose_name='Цена товара 2')),
                ('description', models.CharField(max_length=250, verbose_name='Описание товара')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
            },
        ),
    ]
