# Generated by Django 4.0.3 on 2022-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningchairs',
            name='size',
            field=models.CharField(max_length=250, verbose_name='Размеры'),
        ),
    ]
