# Generated by Django 4.0.3 on 2022-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_diningchairs_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningchairs',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание товара'),
        ),
    ]
